# .streamlit/secrets.toml

[supabase]
# Use descriptive keys like 'url' and 'key'
url = "https://eyvjjjxccbvdacbspdqk.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5dmpqanhjY2J2ZGFjYnNwZHFrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MjEzMzYxMSwiZXhwIjoyMDc3NzA5NjExfQ.G9V79osN7D2SsnWIBJnzDSv3NYmBEotS4-UsNPnISqY"
